services:
  chat_backend:
    build:
      context: .
    container_name: chat_backend
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - chat_network

  db:
    image: postgres:14-alpine
    container_name: chat_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - chat_network

  redis:
    image: redis:7
    container_name: chat_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - chat_network

volumes:
  postgres_data:

networks:
  chat_network:
    driver: bridge
