services:
  chat_backend:
    ports:
      - "127.0.0.1:8000:8000"

  nginx:
    image: nginx:stable-alpine
    container_name: chat_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - chat_backend
    networks:
      - chat_network
