"""add relations

Revision ID: f667f0ad5950
Revises: fa8ba05fe724
Create Date: 2025-03-21 05:13:39.629597

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f667f0ad5950"
down_revision: Union[str, None] = "fa8ba05fe724"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "file_storage", "messages", ["message_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "message_status_message_id_key", "message_status", type_="unique"
    )
    op.create_foreign_key(
        None, "message_status", "messages", ["message_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "message_status", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "messages", "users", ["sender_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "messages", "rooms", ["room_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "room_user", "rooms", ["room_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "room_user", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column("rooms", "created_by", existing_type=sa.INTEGER(), nullable=True)
    op.create_foreign_key(
        None, "rooms", "users", ["created_by"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "user_status", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_status", type_="foreignkey")
    op.drop_constraint(None, "rooms", type_="foreignkey")
    op.alter_column("rooms", "created_by", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint(None, "room_user", type_="foreignkey")
    op.drop_constraint(None, "room_user", type_="foreignkey")
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_constraint(None, "message_status", type_="foreignkey")
    op.drop_constraint(None, "message_status", type_="foreignkey")
    op.create_unique_constraint(
        "message_status_message_id_key", "message_status", ["message_id"]
    )
    op.drop_constraint(None, "file_storage", type_="foreignkey")
    # ### end Alembic commands ###
