"""make created_by room's column not nullable

Revision ID: 413ef3abc459
Revises: 0050cb78486e
Create Date: 2025-05-08 08:23:17.094928

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "413ef3abc459"
down_revision: Union[str, None] = "0050cb78486e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("rooms", "created_by", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("rooms", "created_by", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
